trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

resources: 
  repositories:
  - repository: devops
    endpoint: CodRepo
    type: git
    name: cod/Cod.Infrastructures
    ref: main

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Stage
    steps:
    - task: CopyFiles@2
      displayName: 'Drop Static Website'
      inputs:
        Contents: '$(System.DefaultWorkingDirectory)/src/**'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - publish: $(Build.ArtifactStagingDirectory)/src
      artifact: drop
      
- stage: Production
  jobs:
  - template: pipelines/jobs/StaticWebsiteDeploy.yml@devops
    parameters:
      buildAgentVmImage: 'ubuntu-latest'
      azureServiceConnection: 'niobium-chchwingtyres'
      resourceGroupName: 'niobium-chchwingtyres'
      storageAccountName: 'websitechchwingtyres'
      #cdnCustomDomainName: 'www.chchwingtyres.co.nz'
      enableCdn: false
      checkoutDevopsStep:
        checkout: devops